# Generated by Django 5.2.7 on 2025-12-18 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=20, verbose_name='Categoria')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('ano', models.PositiveIntegerField(verbose_name='Ano')),
                ('combustivel', models.CharField(max_length=20, verbose_name='Combustivel')),
                ('cilindrada', models.PositiveIntegerField(verbose_name='Cilindrada')),
                ('cavalos', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cavalos')),
                ('transmissao', models.CharField(max_length=20, verbose_name='Transmissao')),
                ('quilometragem', models.PositiveIntegerField(verbose_name='Quilometragem')),
                ('matricula', models.CharField(blank=True, max_length=8, null=True, verbose_name='Matricula')),
            ],
        ),
        migrations.CreateModel(
            name='Cronicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('kmsEntreTroca', models.PositiveIntegerField(verbose_name='kms entre troca')),
                ('trocadoNoKm', models.PositiveIntegerField(default=0, verbose_name='Trocado no km')),
                ('risco', models.FloatField(default=0.0, verbose_name='Risco (normalizado)')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.carros')),
            ],
        ),
        migrations.CreateModel(
            name='Definicoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(default='light', max_length=50)),
                ('notificacoes', models.BooleanField(default=True)),
                ('linguagem', models.CharField(default='pt', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Garagens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarrosSalvos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carro_nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('garagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.garagens')),
            ],
        ),
        migrations.AddField(
            model_name='carros',
            name='garagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.garagens'),
        ),
        migrations.CreateModel(
            name='Manutencoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('tipo', models.CharField(max_length=10, verbose_name='Tipo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('quilometragem', models.PositiveIntegerField(verbose_name='Quilometragem')),
                ('custo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data', models.DateField(verbose_name='Data da Manutenção')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.carros')),
            ],
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.TextField(verbose_name='Nota')),
                ('garagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.garagens')),
                ('manutencao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.manutencoes')),
            ],
        ),
        migrations.CreateModel(
            name='Preventivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('diasEntreTroca', models.PositiveIntegerField(verbose_name='Dias entre troca')),
                ('trocadoNaData', models.DateField(verbose_name='Trocado na data')),
                ('kmsEntreTroca', models.PositiveIntegerField(verbose_name='kms entre troca')),
                ('trocadoNoKm', models.PositiveIntegerField(default=0, verbose_name='Trocado no km')),
                ('risco', models.FloatField(default=0.0, verbose_name='Risco (normalizado)')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.carros')),
            ],
        ),
    ]
