# Generated by Django 5.2.7 on 2025-11-14 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('carro_id', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('combustivel', models.CharField(choices=[('Gasolina', 'Gasolina'), ('Gasoleo', 'Gasoleo'), ('Hibrido', 'Hibrido'), ('Eletrico', 'Eletrico'), ('Outro', 'Outro')], max_length=20, verbose_name='Combustivel')),
                ('tdi', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('cavalos', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cavalos')),
                ('transmissao', models.CharField(choices=[('Manual', 'Manual'), ('Automatico', 'Automatico'), ('Semi-automatico', 'Semi-automatico'), ('CVT', 'CVT'), ('Outro', 'Outro')], max_length=20, verbose_name='Transmissao')),
                ('quilometragem', models.PositiveIntegerField(verbose_name='Quilometragem')),
                ('ano_produzido', models.PositiveIntegerField(verbose_name='Ano Produzido')),
                ('tipo_corpo', models.CharField(blank=True, choices=[('Seda', 'Sedã'), ('Hatchback', 'Hatchback'), ('SUV', 'SUV'), ('Cope', 'Cupê'), ('Conversivel', 'Conversível'), ('Carrinha', 'Carrinha'), ('Van', 'Van'), ('Pickup', 'Pickup'), ('Outro', 'Outro')], max_length=20, null=True, verbose_name='Tipo Corpo')),
                ('vin', models.CharField(blank=True, max_length=17, null=True, verbose_name='VIN')),
                ('matricula', models.CharField(blank=True, max_length=8, null=True, verbose_name='Matricula')),
            ],
        ),
        migrations.CreateModel(
            name='Garagem',
            fields=[
                ('garagem_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Cronico',
            fields=[
                ('problema_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('quilometragem', models.PositiveIntegerField(verbose_name='Quilometragem')),
                ('severidade', models.CharField(blank=True, choices=[('nenhuma', 'Nenhuma'), ('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('urgente', 'Urgente')], max_length=7, null=True, verbose_name='Severidade')),
                ('resolvido', models.BooleanField(default=False)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.carro')),
            ],
        ),
        migrations.AddField(
            model_name='carro',
            name='garagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.garagem'),
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('registro_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('custo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data', models.DateField(blank=True, null=True, verbose_name='Dia da Manutenção')),
                ('quilometragem', models.PositiveIntegerField(verbose_name='Quilometragem')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.carro')),
            ],
        ),
        migrations.AddField(
            model_name='garagem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.utilizador'),
        ),
        migrations.CreateModel(
            name='Defenicoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.utilizador')),
            ],
        ),
    ]
