# Generated by Django 5.2.7 on 2025-12-17 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cronicos',
            name='trocarNoKm',
        ),
        migrations.RemoveField(
            model_name='preventivos',
            name='trocarNaData',
        ),
        migrations.RemoveField(
            model_name='preventivos',
            name='trocarNoKm',
        ),
        migrations.AddField(
            model_name='cronicos',
            name='trocadoNoKm',
            field=models.PositiveIntegerField(default=0, verbose_name='Trocado no km'),
        ),
        migrations.AddField(
            model_name='preventivos',
            name='trocadoNaData',
            field=models.DateField(default='2025-12-10', verbose_name='Trocado na data'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preventivos',
            name='trocadoNoKm',
            field=models.PositiveIntegerField(default=0, verbose_name='Trocado no km'),
        ),
    ]
