# Generated by Django 5.2.7 on 2025-12-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carros',
            name='carro_id',
        ),
        migrations.RemoveField(
            model_name='cronicos',
            name='problema_id',
        ),
        migrations.RemoveField(
            model_name='garagens',
            name='garagem_id',
        ),
        migrations.RemoveField(
            model_name='manutencoes',
            name='registro_id',
        ),
        migrations.RemoveField(
            model_name='preventivos',
            name='periodico_id',
        ),
        migrations.AddField(
            model_name='carros',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='cronicos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='garagens',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='manutencoes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='preventivos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
