# Generated by Django 5.2.7 on 2025-12-16 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carros',
            old_name='cc',
            new_name='cilindrada',
        ),
    ]
