# Generated by Django 5.2.7 on 2025-12-18 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notas',
            name='manutencao',
        ),
    ]
