# Generated by Django 5.2.7 on 2025-11-25 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_garagem_user_alter_defenicoes_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carros',
            fields=[
                ('carro_id', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('combustivel', models.CharField(choices=[('gasolina', 'Gasolina'), ('gasoleo', 'Gasoleo'), ('hibrido', 'Hibrido'), ('eletrico', 'Eletrico'), ('outro', 'Outro')], max_length=20, verbose_name='Combustivel')),
                ('tdi', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('cavalos', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cavalos')),
                ('transmissao', models.CharField(choices=[('manual', 'Manual'), ('automatico', 'Automatico'), ('semi-automatico', 'Semi-automatico'), ('cvt', 'CVT'), ('outro', 'Outro')], max_length=20, verbose_name='Transmissao')),
                ('quilometragem', models.PositiveIntegerField(verbose_name='Quilometragem')),
                ('ano_produzido', models.PositiveIntegerField(verbose_name='Ano Produzido')),
                ('tipo_corpo', models.CharField(blank=True, choices=[('seda', 'Sedã'), ('hatchback', 'Hatchback'), ('suv', 'SUV'), ('cope', 'Cupê'), ('conversivel', 'Conversível'), ('carrinha', 'Carrinha'), ('van', 'Van'), ('pickup', 'Pickup'), ('outro', 'Outro')], max_length=20, null=True, verbose_name='Tipo Corpo')),
                ('vin', models.CharField(blank=True, max_length=17, null=True, verbose_name='VIN')),
                ('matricula', models.CharField(blank=True, max_length=8, null=True, verbose_name='Matricula')),
            ],
        ),
        migrations.RemoveField(
            model_name='carro',
            name='garagem',
        ),
        migrations.RemoveField(
            model_name='manutencao',
            name='carro',
        ),
        migrations.RemoveField(
            model_name='garagem',
            name='user',
        ),
        migrations.CreateModel(
            name='Cronicos',
            fields=[
                ('problema_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('kmsEntreTroca', models.PositiveIntegerField(verbose_name='kms entre troca')),
                ('kmTrocado', models.PositiveIntegerField(default=0, verbose_name='Kms na ultima troca')),
                ('risco_normalizado', models.FloatField(default=0.0, verbose_name='Risco (normalizado)')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.carros')),
            ],
        ),
        migrations.CreateModel(
            name='Garagens',
            fields=[
                ('garagem_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='carros',
            name='garagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.garagens'),
        ),
        migrations.CreateModel(
            name='Manutencoes',
            fields=[
                ('registro_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('corretivo', 'Corretivo'), ('preventivo', 'Preventivo'), ('cronico', 'Crônico')], max_length=10, verbose_name='Tipo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('quilometragem', models.PositiveIntegerField(verbose_name='Quilometragem')),
                ('custo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data', models.DateField(verbose_name='Data da Manutenção')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.carros')),
            ],
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.TextField(verbose_name='Nota')),
                ('garagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.garagens')),
            ],
        ),
        migrations.CreateModel(
            name='Preventivos',
            fields=[
                ('periodico_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('dataEntreTroca', models.DateField(blank=True, null=True, verbose_name='Tempo entre troca')),
                ('dataTrocado', models.DateField(blank=True, null=True, verbose_name='Data na ultima troca')),
                ('kmsEntreTroca', models.PositiveIntegerField(verbose_name='kms entre troca')),
                ('kmTrocado', models.PositiveIntegerField(default=0, verbose_name='Kms na ultima troca')),
                ('risco_normalizado', models.FloatField(default=0.0, verbose_name='Risco (normalizado)')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.carros')),
            ],
        ),
        migrations.DeleteModel(
            name='Cronico',
        ),
        migrations.DeleteModel(
            name='Carro',
        ),
        migrations.DeleteModel(
            name='Manutencao',
        ),
        migrations.DeleteModel(
            name='Garagem',
        ),
    ]
