# Generated by Django 5.2.7 on 2025-12-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_cc_carros_cilindrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='carros',
            name='ano',
            field=models.PositiveIntegerField(default=1999, verbose_name='Ano'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carros',
            name='marca',
            field=models.CharField(default='Mercedes', max_length=100, verbose_name='Marca'),
            preserve_default=False,
        ),
    ]
