# Generated by Django 5.2.7 on 2025-12-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_carros_carro_id_remove_cronicos_problema_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cronicos',
            old_name='risco_normalizado',
            new_name='risco',
        ),
        migrations.RenameField(
            model_name='preventivos',
            old_name='risco_normalizado',
            new_name='risco',
        ),
        migrations.AlterField(
            model_name='carros',
            name='combustivel',
            field=models.CharField(max_length=20, verbose_name='Combustivel'),
        ),
        migrations.AlterField(
            model_name='carros',
            name='tipo_corpo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tipo Corpo'),
        ),
        migrations.AlterField(
            model_name='manutencoes',
            name='tipo',
            field=models.CharField(max_length=10, verbose_name='Tipo'),
        ),
    ]
