# Generated by Django 5.2.7 on 2025-12-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_notas_manutencao'),
    ]

    operations = [
        migrations.AddField(
            model_name='carros',
            name='proxima_manutenção',
            field=models.DateField(default='2026-03-14', verbose_name='Data proxima manutenção'),
            preserve_default=False,
        ),
    ]
