# Generated by Django 5.2.7 on 2025-12-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_carros_ano_carros_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carros',
            name='transmissao',
            field=models.CharField(max_length=20, verbose_name='Transmissao'),
        ),
    ]
