# Generated by Django 5.2.7 on 2025-11-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_carros_remove_carro_garagem_remove_manutencao_carro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carros',
            name='tdi',
        ),
        migrations.AddField(
            model_name='carros',
            name='cc',
            field=models.PositiveIntegerField(default=1000, verbose_name='CC'),
            preserve_default=False,
        ),
    ]
