# Generated by Django 5.2.7 on 2025-12-19 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_carros_proxima_manutenção'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carros',
            old_name='proxima_manutenção',
            new_name='proxima_manutencao',
        ),
    ]
