# Generated by Django 5.2.7 on 2025-12-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_carros_transmissao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cronicos',
            name='kmTrocado',
        ),
        migrations.RemoveField(
            model_name='preventivos',
            name='kmTrocado',
        ),
        migrations.AddField(
            model_name='cronicos',
            name='trocarNoKm',
            field=models.PositiveIntegerField(default=0, verbose_name='Trocar no km'),
        ),
        migrations.AddField(
            model_name='preventivos',
            name='trocarNoKm',
            field=models.PositiveIntegerField(default=0, verbose_name='Trocar no km'),
        ),
    ]
