# Generated by Django 5.2.7 on 2025-12-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_proxima_manutenção_carros_proxima_manutencao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronicos',
            name='trocarNoKm',
            field=models.PositiveIntegerField(default=0, verbose_name='Trocar no km'),
        ),
        migrations.AddField(
            model_name='preventivos',
            name='trocarNaData',
            field=models.DateField(default='2027-01-31', verbose_name='Trocar na data'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preventivos',
            name='trocarNoKm',
            field=models.PositiveIntegerField(default=0, verbose_name='Trocar no km'),
        ),
    ]
