# Generated by Django 5.2.7 on 2025-12-19 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cronicos_trocarnokm_preventivos_trocarnadata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carros',
            name='proxima_manutencao',
        ),
    ]
