# Generated by Django 5.2.7 on 2025-12-06 15:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_carros_vin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Defenicoes',
            new_name='Definicoes',
        ),
    ]
