# Generated by Django 5.2.7 on 2025-12-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_carros_proxima_manutencao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronicos',
            name='risco',
            field=models.FloatField(default=0.0, null=True, verbose_name='Risco (normalizado)'),
        ),
        migrations.AlterField(
            model_name='cronicos',
            name='trocadoNoKm',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Trocado no km'),
        ),
        migrations.AlterField(
            model_name='cronicos',
            name='trocarNoKm',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Trocar no km'),
        ),
        migrations.AlterField(
            model_name='preventivos',
            name='risco',
            field=models.FloatField(default=0.0, null=True, verbose_name='Risco (normalizado)'),
        ),
        migrations.AlterField(
            model_name='preventivos',
            name='trocadoNoKm',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Trocado no km'),
        ),
        migrations.AlterField(
            model_name='preventivos',
            name='trocarNoKm',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Trocar no km'),
        ),
    ]
