# Generated by Django 5.2.7 on 2025-12-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_cronicos_risco_alter_cronicos_trocadonokm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preventivos',
            name='trocadoNaData',
            field=models.DateField(null=True, verbose_name='Trocado na data'),
        ),
        migrations.AlterField(
            model_name='preventivos',
            name='trocarNaData',
            field=models.DateField(null=True, verbose_name='Trocar na data'),
        ),
    ]
