# Generated by Django 5.2.7 on 2025-12-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_carros_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carros',
            name='image_url',
        ),
        migrations.AddField(
            model_name='carros',
            name='imagem_url',
            field=models.URLField(blank=True, null=True, verbose_name='Foto URL'),
        ),
    ]
