# Generated by Django 5.2.7 on 2025-12-22 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_carros_image_url_carros_imagem_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrossalvos',
            old_name='carro_nome',
            new_name='nome',
        ),
    ]
