# Generated by Django 5.2.7 on 2025-12-23 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_carro_nome_carrossalvos_nome'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Manutencoes',
            new_name='Corretivos',
        ),
    ]
