# Generated by Django 5.2.7 on 2025-12-24 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_manutencoes_corretivos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarrosSalvos',
            new_name='CarrosGuardados',
        ),
    ]
