# Generated by Django 5.2.7 on 2025-12-26 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_carrossalvos_carrosguardados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corretivos',
            name='custo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
