# Generated by Django 5.2.7 on 2025-12-27 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_corretivos_custo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cronicos',
            name='risco',
        ),
        migrations.RemoveField(
            model_name='preventivos',
            name='risco',
        ),
    ]
