# Generated by Django 5.2.7 on 2025-12-27 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_cronicos_risco_remove_preventivos_risco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrosguardados',
            name='garagem',
        ),
        migrations.AddField(
            model_name='carrosguardados',
            name='carro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.carros'),
            preserve_default=False,
        ),
    ]
