# Generated by Django 5.2.7 on 2025-12-28 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_carrosguardados_garagem_carrosguardados_carro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrosguardados',
            name='carro',
        ),
        migrations.AddField(
            model_name='carrosguardados',
            name='garagem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.garagens'),
            preserve_default=False,
        ),
    ]
