# Generated by Django 5.2.7 on 2025-12-30 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_carrosguardados_carro_carrosguardados_garagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notas',
            name='garagem',
        ),
        migrations.AddField(
            model_name='notas',
            name='carro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.carros'),
            preserve_default=False,
        ),
    ]
