# Generated by Django 5.2.7 on 2025-12-30 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_notas_garagem_notas_carro'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrosImagens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(verbose_name='Nome')),
                ('uuid', models.TextField(verbose_name='UUID')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.carros')),
            ],
        ),
    ]
