# Generated by Django 5.2.7 on 2025-12-30 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_carrosimagens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carros',
            name='imagem_url',
        ),
    ]
