# Generated by Django 5.2.7 on 2025-12-30 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_carros_imagem_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrosimagens',
            name='carro',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='imagem', to='api.carros'),
        ),
        migrations.AlterField(
            model_name='garagens',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
