# Generated by Django 5.2.7 on 2025-11-26 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_carros_tdi_carros_cc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carros',
            name='vin',
        ),
    ]
